services:
  redis:
    image: redis:6.2
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 3s
      retries: 3

  node:
    image: node:22.2.0
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
      - ~/talkn-certs:/etc/ssl/certs
    command: sh -c "npm install && npm run dev"
    ports:
      - '${CH_PORT:-10444}:${CH_PORT:-10444}'
    environment:
      - IS_DOCKER=true
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=${CH_PORT:-6379}
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis-data:
